name: Acceptance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build app
        run: yarn build
        env:
          DOCKER_BUILDKIT: 1

      - name: Start app
        run: yarn start -d

      - name: Run acceptance tests
        run: yarn workspace features test
        env:
          CYPRESS_BASE_URL: http://localhost

      - name: Shutdown app
        if: always()
        run: yarn stop
