name: Deploy

permissions:
  id-token: write
  contents: read

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker images
        run: yarn build
        env:
          DOCKER_BUILDKIT: 1
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
          TAG: ${{ github.ref_name }}

      - name: Publish images to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/mpr-api:$TAG
          docker push $ECR_REGISTRY/mpr-app:$TAG
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
          TAG: ${{ github.ref_name }}

      - name: Use Docker compose CLI
        run: curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

      - name: Add ECS context
        run: docker context create ecs mpr --from-env

      - name: Deploy images to ECS
        run: docker --context mpr compose -f docker-compose.yaml --project-name mpr up
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
          TAG: ${{ github.ref_name }}
